name: object_detection
description: "A Flutter project That uses Tensor Flow Models to detect objects using camera"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  permission_handler: ^11.3.1
  camera: ^0.11.0+2
  image: ^3.3.0
  tflite:
    git:
      url: "https://github.com/mdtuyen/flutter_tflite.git"
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
